// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.2
// source: go.proto

package baidurpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host            string       `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port            int32        `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	TimeoutSenconds int32        `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Methods         []*RPCMethod `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *RPCStatus) Reset() {
	*x = RPCStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCStatus) ProtoMessage() {}

func (x *RPCStatus) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCStatus.ProtoReflect.Descriptor instead.
func (*RPCStatus) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{0}
}

func (x *RPCStatus) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RPCStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RPCStatus) GetTimeout() int32 {
	if x != nil {
		return x.TimeoutSenconds
	}
	return 0
}

func (x *RPCStatus) GetMethods() []*RPCMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type RPCMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service        string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method         string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	InTypeMeta     string `protobuf:"bytes,3,opt,name=InTypeMeta,proto3" json:"InTypeMeta,omitempty"`
	ReturnTypeMeta string `protobuf:"bytes,4,opt,name=ReturnTypeMeta,proto3" json:"ReturnTypeMeta,omitempty"`
}

func (x *RPCMethod) Reset() {
	*x = RPCMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMethod) ProtoMessage() {}

func (x *RPCMethod) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMethod.ProtoReflect.Descriptor instead.
func (*RPCMethod) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{1}
}

func (x *RPCMethod) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RPCMethod) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RPCMethod) GetInTypeMeta() string {
	if x != nil {
		return x.InTypeMeta
	}
	return ""
}

func (x *RPCMethod) GetReturnTypeMeta() string {
	if x != nil {
		return x.ReturnTypeMeta
	}
	return ""
}

type QpsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qpsinfo map[int64]int32 `protobuf:"bytes,1,rep,name=qpsinfo,proto3" json:"qpsinfo,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *QpsData) Reset() {
	*x = QpsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QpsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QpsData) ProtoMessage() {}

func (x *QpsData) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QpsData.ProtoReflect.Descriptor instead.
func (*QpsData) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{2}
}

func (x *QpsData) GetQpsinfo() map[int64]int32 {
	if x != nil {
		return x.Qpsinfo
	}
	return nil
}

var File_go_proto protoreflect.FileDescriptor

var file_go_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x09, 0x52, 0x50,
	0x43, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x50, 0x43,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22,
	0x85, 0x01, 0x0a, 0x09, 0x52, 0x50, 0x43, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x26, 0x0a, 0x0e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x76, 0x0a, 0x07, 0x51, 0x70, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2f, 0x0a, 0x07, 0x71, 0x70, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x51, 0x70, 0x73, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x51, 0x70,
	0x73, 0x69, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x71, 0x70, 0x73, 0x69,
	0x6e, 0x66, 0x6f, 0x1a, 0x3a, 0x0a, 0x0c, 0x51, 0x70, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61,
	0x69, 0x64, 0x75, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x62, 0x61, 0x69, 0x64, 0x75,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_proto_rawDescOnce sync.Once
	file_go_proto_rawDescData = file_go_proto_rawDesc
)

func file_go_proto_rawDescGZIP() []byte {
	file_go_proto_rawDescOnce.Do(func() {
		file_go_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_proto_rawDescData)
	})
	return file_go_proto_rawDescData
}

var file_go_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_go_proto_goTypes = []interface{}{
	(*RPCStatus)(nil), // 0: RPCStatus
	(*RPCMethod)(nil), // 1: RPCMethod
	(*QpsData)(nil),   // 2: QpsData
	nil,               // 3: QpsData.QpsinfoEntry
}
var file_go_proto_depIdxs = []int32{
	1, // 0: RPCStatus.methods:type_name -> RPCMethod
	3, // 1: QpsData.qpsinfo:type_name -> QpsData.QpsinfoEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_go_proto_init() }
func file_go_proto_init() {
	if File_go_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QpsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_proto_goTypes,
		DependencyIndexes: file_go_proto_depIdxs,
		MessageInfos:      file_go_proto_msgTypes,
	}.Build()
	File_go_proto = out.File
	file_go_proto_rawDesc = nil
	file_go_proto_goTypes = nil
	file_go_proto_depIdxs = nil
}
